Add WeChat Online
univapay/univapay-java-sdk pull request #180
Opened 2021-10-14 10:55 UTC by yukimogu

Closes #176 
Add unimplemented other brands
Fix to be able to add body with POST

2021-10-14 12:07 UTC, andrezimmermann requested changes
LGTM, just need to adjust those QR Brands! 😃

2021-10-14 12:07 UTC, andrezimmermann commented on src/main/java/com/univapay/sdk/types/brand/OnlineBrand.java
> +  TRUEMONEY,
These are QR Code brands so I think they don't need to be here 👍

2021-10-14 13:09 UTC, kgston reviewed
Minor stuff 👍

2021-10-14 13:09 UTC, kgston commented on src/main/java/com/univapay/sdk/models/common/CallMethod.java
> +  @SerializedName("APP")
These should be lowercase

2021-10-15 05:17 UTC, andrezimmermann commented on src/main/java/com/univapay/sdk/models/common/CallMethod.java
> +  @SerializedName("APP")
Right, thanks for catching that 👍

2021-10-15 06:36 UTC, andrezimmermann reviewed
Thanks, will merge and release this soon 😄

2021-10-15 06:37 UTC, andrezimmermann approved these changes

2021-10-15 06:55 UTC, merged